### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by matthiasclasen** [grulja/xdg-desktop-portal-kde#1]
I spent a while trying to get this to build on my system, but I think

CMake Error at src/CMakeLists.txt:21 (add_executable):
  Cannot find source file:

```
desktopportal.cpp
```

is just a missing file in git ?

**Comment by grulja** [comment]
That file shouldn't be there, that was just my previous attempt to fix the problem with registering multiple interfaces on same dbus path. Should be fixed now. Be aware that only AppChooser portal will work as it is registered first, if you want to try FileChooser you need to comment the line where I call sessionBus.registerObject(......, appChooser) in xdg-desktop-portal.cpp.
